services:
  ranger-admin:
    # image: ghcr.io/takezoe/ranger-docker/ranger-admin:v2.4.0
    build:
      context: ./ranger-admin
      dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - 6080:6080
    depends_on:
      - ranger-db
      - ranger-solr

  ranger-db:
    image: postgres
    container_name: ranger-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rangeradmin
      POSTGRES_PASSWORD: rangeradmin
      POSTGRES_DB: ranger

  ranger-solr:
    image: solr:8.11.2
    container_name: ranger-solr
    ports:
      - 8983:8983
    volumes:
      - ./ranger-solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits
