volumes:
  ranger-db:
  ranger-solr:
services:
  ranger-admin:
    # image: ghcr.io/takezoe/ranger-docker/ranger-admin:v2.4.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ranger-admin.rule=Host(`ranger.flavindias.com.br`)"
      - "traefik.http.services.ranger-admin.loadbalancer.server.port=6080"
      - "traefik.http.routers.ranger-admin.entrypoints=web,websecure"
      - "traefik.http.routers.ranger-admin.middlewares=redirect-to-https"
      - "traefik.http.routers.ranger-admin-secure.tls=true"
      - "traefik.http.routers.ranger-admin-secure.tls.certresolver=letsencrypt"
    build:
      context: ./ranger-admin
      dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - 6080:6080
    depends_on:
      - ranger-db
      - ranger-solr

  ranger-db:
    image: postgres
    container_name: ranger-db
    volumes:
      - ranger-db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: rangeradmin
      POSTGRES_PASSWORD: rangeradmin
      POSTGRES_DB: ranger

  ranger-solr:
    image: solr:8.11.2
    container_name: ranger-solr
    ports:
      - 8983:8983
    volumes:
      - ranger-solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits
